apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx
data:
  api.conf: |
      server {
            listen 80;

            client_max_body_size 1G;

            server_name _;

            location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_redirect off;
                proxy_pass http://backend;
            }

        }

        upstream backend {
            server localhost:8000;
        }