version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s

  backend:
    # build:
    #   context: .
    #   dockerfile: backend.dockerfile
    image: "ghcr.io/jgenc/devops-backend:latest"
    # Not giving envfile for now
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  backend-migrate:
    command: bash -c "cd app/ && alembic upgrade head"
    # build:
    #   context: .
    #   dockerfile: backend.dockerfile
    image: "ghcr.io/jgenc/devops-backend:latest"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

  frontend:
    # build:
    #   context: .
    #   dockerfile: //frontend/production.dockerfile
    image: "ghcr.io/jgenc/devops-frontend-prod:latest"
    ports:
      - "80:80"
    depends_on:
      - backend-migrate
    restart: on-failure:5
