webserver:
  hosts:
    vagrant-backend:
      ansible_host: backend
      user: vagrant 
    vagrant-frontend:
      ansible_host: frontend
      user: vagrant 
    azure-deploy-1:
      ansible_host: devops-azure-vm-1
      user: azureuser
    azure-deploy-2:
      ansible_host: devops-azure-vm-2
      user: azureuser

database:
  hosts:
    vagrant-db:
      ansible_host: db
      user: vagrant 
    azure-deploy-1:
      ansible_host: devops-azure-vm-1
      user: azureuser
    azure-deploy-2:
      ansible_host: devops-azure-vm-2
      user: azureuser