webserver:
  hosts:
    vagrant-backend:
      ansible_host: backend
    vagrant-frontend:
      ansible_host: frontend
    azure-deploy-1:
      ansible_host: devops-azure-vm-1
    azure-deploy-2:
      ansible_host: devops-azure-vm-2

database:
  hosts:
    vagrant-db:
      ansible_host: db
    azure-deploy-1:
      ansible_host: devops-azure-vm-1
    