- name: Save Backend's IP
  hosts: backend
  tasks:
    - name: Save Backend's address
      ansible.builtin.debug:
        var: ansible_all_ipv4_addresses
      register: backend_ip

- name: Frontend
  hosts: frontend
  vars:
    nodejs_version: 18
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    # - name: Get PPA script to install Node v18.x
    #   ansible.builtin.get_url:
    #     url: https://deb.nodesource.com/setup_18.x
    #     dest: "/home/{{ user }}/nodesource_setup.sh"
        
    # - name: Run PPA Script
    #   ansible.builtin.command: "bash /home/{{ user }}/nodesource_setup.sh"
    #   become: true
    #   become_user: root

    - name: Installing GPG key for the nodejs LTS repo
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
      become: true
      become_user: root

    - name: Install nodejs LTS repo
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
      become: true
      become_user: root

    - name: Ensure npm and node are installed
      ansible.builtin.apt:
        name:
          - nodejs
        update_cache: true
      become: true
      become_user: root

    - name: Clone frontend repo
      ansible.builtin.git:
        repo: https://github.com/jgenc/hua-distributed-project-frontend
        clone: true
        update: true
        dest: "{{ frontend_workspace }}"

    - name: Install npm packages
      community.general.npm:
        path: "{{ frontend_workspace }}"

    - name: Copying env file
      ansible.builtin.command: "cp {{ frontend_workspace }}/.env.example {{ frontend_workspace }}/.env"
      register: dotenv_copy_cmd_output
      changed_when: dotenv_copy_cmd_output != 0

    - name: Changing backend URL in .env to correspond to backend's IP
      ansible.builtin.lineinfile:
        path: "{{ frontend_workspace }}/.env"
        regexp: "^VITE_SOLID_BACKEND="
        line: "VITE_SOLID_BACKEND=http://{{ hostvars['backend']['backend_ip'].ansible_all_ipv4_addresses[0] }}:{{ backend_app_port }}"

    - name: Build frontend files
      ansible.builtin.command:
        chdir: "{{ frontend_workspace }}"
        cmd: npm run build
    
- name: Install nginx service
  hosts: frontend
  become: true
  become_user: root
  tasks:
    - name: Install nginx from APT
      ansible.builtin.apt:
        name: nginx
        update_cache: true

    - name: Copy nginx configuration 
      ansible.builtin.template:
        src: ../files/frontend/nginx.conf.jinja
        dest: /etc/nginx/sites-available/frontend
    
    # - name: Fix nginx permissions
    #   ansible.builtin.file:
    #     path: "/home/{{ user }}"
    #     mode: ugo+x

    - name: Enable frontend site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/frontend
        dest: /etc/nginx/sites-enabled/frontend
        state: link

    - name: De-activate default nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx


  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: true
